### PR TITLE
Added feature for m.notice-type messages not be bridged

### PR DESCRIPTION
**Pull request by bramenn**
Added feature for m.notice-type messages not be bridged

### CODE REVIEW

**Review by tulir — APPROVED** [review]

**Comment by immanuelfodor** [comment]
What is the impact of this PR? What will or will not be bridged through this? Could you please provide a real life example of such notice message?

**Comment by bramenn** [comment]
> What is the impact of this PR? What will or will not be bridged through this? Could you please provide a real life example of such notice message? 

Impact on m.notice-type events, the idea is that there can be messages (notices) in the rooms, which are not necessarily bypassed, the reason may vary, but in my particular case, I have a development where it is normal to generate notices to take notes related to a specified chat and that the person in the room does not receive this note. 
e.g:

**Comment by bramenn** [comment]
> What is the impact of this PR? What will or will not be bridged through this? Could you please provide a real life example of such notice message? 

Moreover, this functionality is already available in WhatsApp and telegram bridges, and according to what I have seen in the bridges, there is behaviour that is repeated, in conclusion it is normal to have this feature.

**Comment by immanuelfodor** [comment]
Thank you for the explanation. So the default is to bridge these notices and it can be useful to turn this off in such cases.

**Pull request merged**
